# handle prerequisite tasks
- name: "Perform prerequisite actions"
  include: pre.yml

# set up certificates
- name: "Certificate configuration and distribution"
  include: certs.yml

- name: "Configure IPSec Group Encryption"
  include: ipsec-group.yml
  when: libreswan_version | version_compare('3.19', '>=')

- name: "Configure IPSec Peer-to-Peer Encryption"
  include: ipsec-peer.yml
  when: libreswan_version | version_compare('3.19', '<')

- name: "Configure firewall"
  include: firewall.yml

- name: "Finalize service configuration"
  include: finalize.yml
